
trigger:
- main

pool:
  Default

steps:
  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'init'
      backendServiceArm: 'connectionname'
      backendAzureRmStorageAccountName: 'myfirststorage123so'
      backendAzureRmContainerName: 'storage1234'
      backendAzureRmKey: 'dev.tfstate'
      workingDirectory: '$(System.DefaultWorkingDirectory)/main'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'plan'
      workingDirectory: '$(System.DefaultWorkingDirectory)/main'
      environmentServiceNameAzureRM: 'connectionname'

  - task: TerraformTask@5
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '$(System.DefaultWorkingDirectory)/main'
      environmentServiceNameAzureRM: 'connectionname'
